<?php
require_once '../models/AuthManager.php';
AuthManager::checkRole('admin');

require_once '../models/OrderManager.php';

$orderManager = new OrderManager();

// Ambil filter tanggal dari parameter
$startDate = isset($_GET['start_date']) && $_GET['start_date'] !== '' ? $_GET['start_date'] : null;
$endDate = isset($_GET['end_date']) && $_GET['end_date'] !== '' ? $_GET['end_date'] : null;

// Ambil data statistik dan produk terlaris
$stats = $orderManager->getSalesStatistics($startDate, $endDate);
$topProducts = $orderManager->getTopSellingProducts($startDate, $endDate);
$allOrders = $orderManager->getAllOrdersWithUserDetails($startDate, $endDate);

// Generate filename dengan tanggal
$dateRange = '';
if ($startDate && $endDate) {
    $dateRange = '_' . $startDate . '_to_' . $endDate;
} elseif ($startDate) {
    $dateRange = '_from_' . $startDate;
} elseif ($endDate) {
    $dateRange = '_until_' . $endDate;
}
$filename = 'Laporan_Penjualan' . $dateRange . '_' . date('Y-m-d_His') . '.csv';

// Set headers untuk download CSV
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

// Output stream
$output = fopen('php://output', 'w');

// BOM untuk UTF-8 (agar Excel bisa baca special characters)
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

// === HEADER LAPORAN ===
fputcsv($output, ['╔════════════════════════════════════════════════════════════════╗']);
fputcsv($output, ['║          LAPORAN PENJUALAN - PARFUMMY STORE                    ║']);
fputcsv($output, ['╚════════════════════════════════════════════════════════════════╝']);
fputcsv($output, []);

// Informasi Laporan
fputcsv($output, ['Tanggal Export', date('d F Y, H:i:s')]);
if ($startDate || $endDate) {
    $periodText = '';
    if ($startDate && $endDate) {
        $periodText = date('d M Y', strtotime($startDate)) . ' s/d ' . date('d M Y', strtotime($endDate));
        $days = (strtotime($endDate) - strtotime($startDate)) / (60 * 60 * 24) + 1;
        fputcsv($output, ['Periode Laporan', $periodText . ' (' . $days . ' hari)']);
    } elseif ($startDate) {
        $periodText = 'Dari ' . date('d M Y', strtotime($startDate));
        fputcsv($output, ['Periode Laporan', $periodText]);
    } else {
        $periodText = 'Sampai ' . date('d M Y', strtotime($endDate));
        fputcsv($output, ['Periode Laporan', $periodText]);
    }
} else {
    fputcsv($output, ['Periode Laporan', 'Semua Data']);
}
fputcsv($output, ['Generated By', 'Admin (ParfumMy System)']);
fputcsv($output, []);
fputcsv($output, ['═══════════════════════════════════════════════════════════════']);
fputcsv($output, []);

// === RINGKASAN STATISTIK ===
fputcsv($output, ['┌─────────────────────── RINGKASAN STATISTIK ───────────────────────┐']);
fputcsv($output, []);
fputcsv($output, ['Metrik', 'Nilai']);
fputcsv($output, ['─────────────────────', '─────────────────────']);
fputcsv($output, ['Total Pendapatan', 'Rp ' . number_format($stats['total_revenue'], 0, ',', '.')]);
fputcsv($output, ['Total Pesanan', number_format($stats['total_orders']) . ' pesanan']);
if ($stats['total_orders'] > 0) {
    $avgOrder = $stats['total_revenue'] / $stats['total_orders'];
    fputcsv($output, ['Rata-rata per Pesanan', 'Rp ' . number_format($avgOrder, 0, ',', '.')]);
}
fputcsv($output, []);
fputcsv($output, ['└───────────────────────────────────────────────────────────────────┘']);
fputcsv($output, []);

// === PRODUK TERLARIS ===
fputcsv($output, ['┌─────────────────────── PRODUK TERLARIS ───────────────────────────┐']);
fputcsv($output, []);
fputcsv($output, ['No', 'Nama Produk', 'Ukuran', 'Qty Terjual', 'Total Pendapatan', 'Persentase']);
fputcsv($output, ['───', '─────────────────────', '────────', '───────────', '─────────────────', '──────────']);

if (!empty($topProducts)) {
    $no = 1;
    $totalQty = 0;
    $totalRev = 0;
    
    // Hitung total untuk persentase
    foreach ($topProducts as $product) {
        $totalQty += $product['total_quantity'];
        $totalRev += $product['total_revenue'];
    }
    
    foreach ($topProducts as $product) {
        $percentage = $totalRev > 0 ? ($product['total_revenue'] / $totalRev * 100) : 0;
        $ukuran = isset($product['ukuran']) ? $product['ukuran'] . ' ml' : '-';
        
        fputcsv($output, [
            $no++,
            $product['nama'],
            $ukuran,
            number_format($product['total_quantity']) . ' unit',
            'Rp ' . number_format($product['total_revenue'], 0, ',', '.'),
            number_format($percentage, 1) . '%'
        ]);
    }
    
    // Total row
    fputcsv($output, ['───', '─────────────────────', '────────', '───────────', '─────────────────', '──────────']);
    fputcsv($output, ['', 'TOTAL', '', number_format($totalQty) . ' unit', 'Rp ' . number_format($totalRev, 0, ',', '.'), '100%']);
} else {
    fputcsv($output, ['', 'Tidak ada data produk untuk periode ini', '', '', '', '']);
}
fputcsv($output, []);
fputcsv($output, ['└───────────────────────────────────────────────────────────────────┘']);
fputcsv($output, []);

// === DAFTAR PESANAN ===
fputcsv($output, ['┌─────────────────────── DAFTAR PESANAN ────────────────────────────┐']);
fputcsv($output, []);
fputcsv($output, ['No', 'ID Pesanan', 'Pelanggan', 'Tanggal', 'Total Harga', 'Pembayaran', 'Status']);
fputcsv($output, ['───', '──────────', '─────────────', '──────────────', '─────────────', '──────────', '─────────']);

if (!empty($allOrders)) {
    $no = 1;
    $statusCount = [];
    $paymentCount = [];
    
    foreach ($allOrders as $order) {
        $displayNo = !empty($order['nomor_pesanan']) ? $order['nomor_pesanan'] : '#' . $order['id'];
        $payment = $order['metode_pembayaran'] ?? 'N/A';
        $status = $order['status'];
        
        // Count for summary
        $statusCount[$status] = ($statusCount[$status] ?? 0) + 1;
        $paymentCount[$payment] = ($paymentCount[$payment] ?? 0) + 1;
        
        fputcsv($output, [
            $no++,
            $displayNo,
            $order['username'],
            date('d/m/Y H:i', strtotime($order['tanggal_pesanan'])),
            'Rp ' . number_format($order['total_harga'], 0, ',', '.'),
            $payment,
            $status
        ]);
    }
    
    fputcsv($output, []);
    fputcsv($output, ['└───────────────────────────────────────────────────────────────────┘']);
    fputcsv($output, []);
    
    // Summary by Status
    fputcsv($output, ['RINGKASAN BERDASARKAN STATUS:']);
    fputcsv($output, ['Status', 'Jumlah Pesanan', 'Persentase']);
    fputcsv($output, ['─────────────────', '──────────────', '──────────']);
    foreach ($statusCount as $status => $count) {
        $percentage = ($count / count($allOrders)) * 100;
        fputcsv($output, [$status, $count . ' pesanan', number_format($percentage, 1) . '%']);
    }
    
    fputcsv($output, []);
    
    // Summary by Payment Method
    fputcsv($output, ['RINGKASAN METODE PEMBAYARAN:']);
    fputcsv($output, ['Metode', 'Jumlah Pesanan', 'Persentase']);
    fputcsv($output, ['─────────────────', '──────────────', '──────────']);
    foreach ($paymentCount as $payment => $count) {
        $percentage = ($count / count($allOrders)) * 100;
        fputcsv($output, [$payment, $count . ' pesanan', number_format($percentage, 1) . '%']);
    }
} else {
    fputcsv($output, ['', 'Tidak ada pesanan untuk periode ini', '', '', '', '', '']);
    fputcsv($output, []);
    fputcsv($output, ['└───────────────────────────────────────────────────────────────────┘']);
}

fputcsv($output, []);
fputcsv($output, ['═══════════════════════════════════════════════════════════════']);
fputcsv($output, []);
fputcsv($output, ['LAPORAN DIBUAT OLEH SISTEM PARFUMMY']);
fputcsv($output, ['Website: www.parfummy.com']);
fputcsv($output, ['Support: admin@parfummy.com']);
fputcsv($output, []);
fputcsv($output, ['--- End of Report ---']);

fclose($output);
exit;
